seed: 42
k_steps: 4
batch_size: 1024
grad_accum: 1
num_workers: 4
lr: 1.0e-4
lr_min: 1.0e-5
weight_decay: 5.0e-3
max_epochs: 100
steps_per_epoch: 375
amp: true
grad_clip: 1.0
lambda_vel: 1.25
lambda_com: 1.0e-1
lambda_force: 0.0
lambda_struct_bond: 5.0e-2
lambda_struct_angle: 1.0e-2
lambda_struct_dihedral: 5.0e-3
val_every_steps: 100
checkpoint_every_steps: 1000
checkpoint_dir: outputs/checkpoints_aug_wide
log_dir: outputs/logs_aug_wide
resume: null
wandb:
  enabled: true
  project: md-kstep
  entity: dcerrone-dexterity3d
  run_name: null
random_rotate: true
random_rotate_mode: batch
struct_max_bonds: 256
struct_max_angles: 256
struct_max_dihedrals: 256
