name: kstep
channels:
  - conda-forge
  - pytorch
  - defaults
  - nvidia
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - pandas
  - pyyaml
  - tqdm
  - cuda-toolkit=12.1  # if on NVIDIA GPU; ignore on CPU/Mac
  - openmm=8.*
  - mdtraj
  - mdanalysis
  - matplotlib
  - seaborn
  - ambertools
  - openff-toolkit
  - openmmforcefields
  - pip:
      - torch==2.*
      - torchvision==0.*
      - torchaudio==2.*
      - hydra-core
      - wandb
      - rdkit-pypi
      - torchmd-net
      - e3nn
      - torch_geometric
      - line_profiler
      - rich
